
parameters:
  - name: templateParam
    displayName: Template Parameter
    type: string
    default: a template parameter
  - name: templateParam2
    displayName: Template Parameter
    type: string

stages:
  - template: asuperTemplate.yml
    parameters:
      superParam: this is a superParam
  - stage: TemplateStage1
    dependsOn:
      - Stage0
    displayName: TemplateStage 1
    jobs:
      - job: TemplateJob1
        variables:
          aStageVar: $[ stageDependencies.Stage0.Job0.outputs['Script00.stageValue'] ]
        displayName: Template Job 1
        steps:
          - checkout: none
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo "my value 1(set from stage dependencies) does not appear because templates are expanded first before stages are run ---$aStageVar---"
                myValue=`echo ${{ parameters.templateParam }}`
                echo "Template Param 1 ---$myValue---"
                myValue=`echo ${{ parameters.templateParam2 }}`
                echo "Template Param 2 ---$myValue---"
                echo "A Stage Value from main script ---$(aStageVar)---"
            displayName: Template Bash script to output parameters
            name: TemplateScript11